id: MobileironCLOUD Incident Action Playbook
version: -1
name: MobileironCLOUD Incident Action Playbook
description: General Incident Actions Playbook
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 69fd71d0-09c7-4ee0-85ab-2eec73981b82
    type: start
    task:
      id: 69fd71d0-09c7-4ee0-85ab-2eec73981b82
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: b85a3826-98d2-49a0-856d-6e7107b9e534
    type: condition
    task:
      id: b85a3826-98d2-49a0-856d-6e7107b9e534
      version: -1
      name: Select Action
      description: Device specific actions
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      FORCE CHECKIN:
      - "6"
      RETIRE DEVICE:
      - "4"
      SEND MESSAGE:
      - "7"
      UNLOCK DEVICE:
      - "3"
      WIPE DEVICE:
      - "5"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: abef7736-3387-4017-8501-6499fe0eabb3
    type: regular
    task:
      id: abef7736-3387-4017-8501-6499fe0eabb3
      version: -1
      name: UNLOCK DEVICE
      description: Unlock device action
      script: MobileironCLOUD|||mobileiron-unlock-device
      type: regular
      iscommand: true
      brand: MobileironCLOUD
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      device_id:
        simple: ${incident.deviceid}
      platform:
        simple: ${incident.os}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: 0b46d9f2-352e-4cba-8ec2-5389607dee0d
    type: regular
    task:
      id: 0b46d9f2-352e-4cba-8ec2-5389607dee0d
      version: -1
      name: RETIRE DEVICE
      description: Retire device action
      script: MobileironCLOUD|||mobileiron-retire-device
      type: regular
      iscommand: true
      brand: MobileironCLOUD
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      device-id: {}
      device_id:
        simple: ${incident.deviceid}
      platform:
        simple: ${incident.os}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: eecb9ac9-ea55-4fe7-8f2f-40fdda20a9f4
    type: regular
    task:
      id: eecb9ac9-ea55-4fe7-8f2f-40fdda20a9f4
      version: -1
      name: WIPE DEVICE
      description: Wipe device action
      script: MobileironCLOUD|||mobileiron-wipe-device
      type: regular
      iscommand: true
      brand: MobileironCLOUD
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      device_id:
        simple: ${incident.deviceid}
      platform:
        simple: ${incident.os}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: 8db63162-7d0f-4d9c-8f0a-202f99ae3fa2
    type: regular
    task:
      id: 8db63162-7d0f-4d9c-8f0a-202f99ae3fa2
      version: -1
      name: FORCE CHECKIN
      description: Force check-in action
      script: MobileironCLOUD|||mobileiron-force-check-in
      type: regular
      iscommand: true
      brand: MobileironCLOUD
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      device_id:
        simple: ${incident.deviceid}
      platform:
        simple: ${incident.os}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: 52c19543-b8a5-4a58-8f52-0b8355a21cf7
    type: regular
    task:
      id: 52c19543-b8a5-4a58-8f52-0b8355a21cf7
      version: -1
      name: SEND MESSAGE
      description: Send message action
      script: MobileironCLOUD|||mobileiron-send-message
      type: regular
      iscommand: true
      brand: MobileironCLOUD
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      device_id:
        simple: ${incident.deviceid}
      platform:
        simple: ${incident.os}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: 07bdc487-c8cc-4373-8ff5-75a40c6e5053
    type: title
    task:
      id: 07bdc487-c8cc-4373-8ff5-75a40c6e5053
      version: -1
      name: CLOSE
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {
      "2_6_FORCE CHECKIN": 0.35
    },
    "paper": {
      "dimensions": {
        "height": 560,
        "width": 2100,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
tests:
- No tests (auto formatted)
fromversion: 6.0.0
